### ISSUE TITLE
Status: Failed to start: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by RichFind** [scallybmHome/signalk-raspberry-pi-ina219hat#2]
Status: Failed to start: Cannot read properties of undefined (reading 'length')

I am using Pi 4 with Bullseye if that could make a difference.

Sure would be great to get this working.

Here is the logfile:

Oct 29 15:17:39 signalk-postgsail:Token is required
Oct 29 15:17:39 error starting plugin: TypeError: Cannot read properties of undefined (reading 'length')
Oct 29 15:17:39 TypeError: Cannot read properties of undefined (reading 'length') at Object.plugin.start (/home/pi/.signalk/node_modules/signalk-rpi-ina219hat/index.js:158:73) at doPluginStart (/usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:271:20) at doRegisterPlugin (/usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:394:13) at registerPlugin (/usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:225:13) at /usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:176:13 at Array.forEach (<anonymous>) at startPlugins (/usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:175:70) at Object.start (/usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:40:13) at /usr/lib/node_modules/signalk-server/lib/index.js:438:70 at /usr/lib/node_modules/signalk-server/node_modules/lodash/lodash.js:4967:15 at Function.forIn (/usr/lib/node_modules/signalk-server/node_modules/lodash/lodash.js:13018:11) at startInterfaces (/usr/lib/node_modules/signalk-server/lib/index.js:428:22) at /usr/lib/node_modules/signalk-server/lib/index.js:275:17 at createServer (/usr/lib/node_modules/signalk-server/lib/index.js:395:5) at /usr/lib/node_modules/signalk-server/lib/index.js:264:13 at new Promise (<anonymous>) at Server.start (/usr/lib/node_modules/signalk-server/lib/index.js:263:16) at Object.<anonymous> (/usr/lib/node_modules/signalk-server/bin/signalk-server:26:8) at Module._compile (node:internal/modules/cjs/loader:1155:14) at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10) at Module.load (node:internal/modules/cjs/loader:1033:32) at Function.Module._load (node:internal/modules/cjs/loader:868:12)

**Comment by RichFind** [comment]
Still have this problem. Any chance you could please take a look at it? I would really appreciate if you could fix this issue.

![Screenshot 2022-11-03 120546](https://user-images.githubusercontent.com/19277463/199773025-8ca9838a-a217-4d93-a99a-780dc4110586.jpg)

This Plugin is titled signalk-rpi-ina219hat, I assume there isn't a reason that I can't use with the ina219 just connected to the I/O pins on the Pi.

The sensor is showing up on the bus.

pi@openplotter:~ $ i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:                         -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: 40 -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --             

The problem seems to originate from the following lines in index.js

158   app.debug('INA219hat:start - length of options %s', options.channel.length.toString());
159  
160    if (options. Channel && options.channel.length > 0){

I am not a programmer so I don't know how to fix the issue.

Latest log file:

Nov 03 11:04:07 2022-11-03T15:04:07.900Z signalk-rpi-ina219hat INA219hat:start
Nov 03 11:04:07 error starting plugin: TypeError: Cannot read properties of undefined (reading 'length')
Nov 03 11:04:07 TypeError: Cannot read properties of undefined (reading 'length') at Object.plugin.start (/home/pi/.signalk/node_modules/signalk-rpi-ina219hat/index.js:158:73) at doPluginStart (/usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:271:20) at doRegisterPlugin (/usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:394:13) at registerPlugin (/usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:225:13) at /usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:176:13 at Array.forEach (<anonymous>) at startPlugins (/usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:175:70) at Object.start (/usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:40:13) at /usr/lib/node_modules/signalk-server/lib/index.js:438:70 at /usr/lib/node_modules/signalk-server/node_modules/lodash/lodash.js:4967:15 at Function.forIn (/usr/lib/node_modules/signalk-server/node_modules/lodash/lodash.js:13018:11) at startInterfaces (/usr/lib/node_modules/signalk-server/lib/index.js:428:22) at /usr/lib/node_modules/signalk-server/lib/index.js:275:17 at createServer (/usr/lib/node_modules/signalk-server/lib/index.js:395:5) at /usr/lib/node_modules/signalk-server/lib/index.js:264:13 at new Promise (<anonymous>) at Server.start (/usr/lib/node_modules/signalk-server/lib/index.js:263:16) at Object.<anonymous> (/usr/lib/node_modules/signalk-server/bin/signalk-server:26:8) at Module._compile (node:internal/modules/cjs/loader:1155:14) at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10) at Module.load (node:internal/modules/cjs/loader:1033:32) at Function.Module._load (node:internal/modules/cjs/loader:868:12)

**Comment by huwi** [comment]
Hi.
I have the same problem.  I tried the plugin with nodejs 18 and 20. same result.

Here the log:

Oct 17 13:10:15 error starting plugin: TypeError: Cannot read properties of undefined (reading 'length')
Oct 17 13:10:15 TypeError: Cannot read properties of undefined (reading 'length') at plugin.start (/home/boat/.signalk/node_modules/signalk-rpi-ina219hat/index.js:158:73) at doPluginStart (/usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:266:20) at /usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:445:21 at savePluginOptions (/usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:132:13) at /usr/lib/node_modules/signalk-server/lib/interfaces/plugins.js:432:13 at Layer.handle [as handle_request] (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/layer.js:95:5) at next (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/route.js:144:13) at Route.dispatch (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/route.js:114:3) at Layer.handle [as handle_request] (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/layer.js:95:5) at /usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:284:15 at Function.process_params (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:346:12) at next (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:280:10) at Function.handle (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:175:3) at router (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:47:12) at Layer.handle [as handle_request] (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/layer.js:95:5) at trim_prefix (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:328:13) at /usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:286:9 at Function.process_params (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:346:12) at next (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:280:10) at ZIP (/usr/lib/node_modules/signalk-server/node_modules/express-easy-zip/index.js:133:3) at Layer.handle [as handle_request] (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/layer.js:95:5) at trim_prefix (/usr/lib/node_modules/signalk-server/node_modules/express/lib/router/index.js:328:13)
Oct 17 13:10:15 POST /skServer/plugins/signalk-raspberry-pi-ina219hat/config 200 7.835 ms - 61

Thank you for your great work!
Kind Regards, Hubert
